import React from 'react';
import { Link } from 'react-router-dom';
import Seo from './Seo';
import { useLanguage } from './language-state';

function Aura({ focus = false, label = 'Aura' }) {
  return <svg className="ora-v2__aura" viewBox="0 0 140 150" aria-label={label} role="img"><ellipse cx="70" cy="138" rx="42" ry="8" fill="#e8def6"/><path d="M72 9c7 19-4 25 12 35 25 15 39 34 35 61-4 28-23 43-49 43-30 0-51-18-50-46 1-22 12-37 29-49 12-9 18-20 23-44Z" fill="#fff9eb" stroke="#18234d" strokeWidth="3"/><path d="M24 91c-13-4-18 3-16 11 2 8 9 11 17 8M116 88c13-7 20-2 19 7-1 8-7 13-17 12" fill="none" stroke="#18234d" strokeWidth="3" strokeLinecap="round"/><ellipse cx="55" cy="91" rx="5" ry="8" fill="#18234d"/><ellipse cx="88" cy="91" rx="5" ry="8" fill="#18234d"/><path d={focus ? 'M64 111c5-3 11-3 16 0' : 'M63 107c5 11 15 11 21 0'} fill={focus ? 'none' : '#f36d67'} stroke="#18234d" strokeWidth="3" strokeLinecap="round"/><path d="M41 108h10M96 108h10" stroke="#efb7b0" strokeWidth="5" strokeLinecap="round"/></svg>;
}

const bars = [18, 38, 25, 56, 34, 74, 45, 26, 64, 36, 52, 22];

function StatusBar() { return <div className="ora-v2__status"><b>9:41</b><i /><span>● ●</span></div>; }

function Phone({ screen }) {
  return <div className="ora-v2__phone"><div className="ora-v2__notch"/><StatusBar />{screen}</div>;
}

function DiscoverScreen({ tr }) {
  const items = [[tr('Improvisation','Improvisation','Improvisación'),tr('Un mot, une idée, une minute.','One word, one idea, one minute.','Una palabra, una idea, un minuto.')],[tr('Convaincs-moi','Convince me','Convénceme'),tr('Défends une opinion clairement.','Defend an opinion clearly.','Defiende una opinión con claridad.')],[tr('Entretien','Interview','Entrevista'),tr('Réponds sans perdre le fil.','Answer without losing your train of thought.','Responde sin perder el hilo.')],['Startup pitch',tr('Présente ton idée en 60 secondes.','Present your idea in 60 seconds.','Presenta tu idea en 60 segundos.')]];
  return <div className="ora-v2__screen ora-v2__discover"><div className="ora-v2__logo">OR<span>A</span></div><h3>{tr('Choisis ton défi du jour.','Choose today’s challenge.','Elige el reto de hoy.')}</h3><p>{tr('Développe ta confiance en quelques minutes.','Build confidence in just a few minutes.','Gana confianza en pocos minutos.')}</p><div className="ora-v2__list">{items.map(([title, text], i)=><article key={title} className={i===0?'is-picked':''}><span>0{i+1}</span><div><b>{title}</b><small>{text}</small></div><i>→</i></article>)}</div></div>;
}

function PracticeScreen({ tr }) {
  return <div className="ora-v2__screen ora-v2__practice"><div className="ora-v2__step">{tr('DÉFI 01','CHALLENGE 01','RETO 01')} <span>{tr('EN COURS','IN PROGRESS','EN CURSO')}</span></div><div className="ora-v2__timer">0:45</div><h3>{tr('Parle de ton plat préféré.','Talk about your favourite dish.','Habla de tu plato favorito.')}</h3><div className="ora-v2__mascot-wrap"><Aura focus label={tr('Aura, le compagnon ORA','Aura, the ORA companion','Aura, el compañero de ORA')}/><small>{tr('Respire. Prends ton temps.','Breathe. Take your time.','Respira. Tómate tu tiempo.')}</small></div><div className="ora-v2__wave">{bars.map((h,i)=><i key={i} style={{height:h}}/>)}</div><button><span/> {tr('Terminer le défi','Finish challenge','Terminar el reto')}</button></div>;
}

function ProgressScreen({ tr }) {
  return <div className="ora-v2__screen ora-v2__progress"><div className="ora-v2__logo">OR<span>A</span></div><div className="ora-v2__result"><Aura label={tr('Aura, le compagnon ORA','Aura, the ORA companion','Aura, el compañero de ORA')}/><small>+50 XP</small><h3>{tr('Ton profil s’affine.','Your profile is evolving.','Tu perfil evoluciona.')}</h3><p>{tr('ORA retient les signaux utiles pour adapter le prochain défi.','ORA keeps useful signals to adapt the next challenge.','ORA conserva las señales útiles para adaptar el siguiente reto.')}</p></div><div className="ora-v2__score"><article><small>{tr('STRUCTURE','STRUCTURE','ESTRUCTURA')}</small><b>84</b><span><i style={{width:'84%'}}/></span></article><article><small>{tr('AISANCE','FLUENCY','FLUIDEZ')}</small><b>76</b><span><i style={{width:'76%'}}/></span></article></div><div className="ora-v2__tip"><small>{tr('PROCHAINE MISSION','NEXT MISSION','PRÓXIMA MISIÓN')}</small><b>{tr('Conclure une idée en une phrase mémorable.','Conclude an idea with one memorable sentence.','Concluir una idea con una frase memorable.')}</b></div><button>{tr('Voir mon Communication DNA','View my Communication DNA','Ver mi Communication DNA')}</button></div>;
}

function CoachingLoop({ tr }) {
  const steps = [
    ['01', tr('Mission','Mission','Misión'), tr('Un défi court choisi selon ton objectif.','A short challenge selected for your goal.','Un reto breve elegido según tu objetivo.')],
    ['02', tr('Pratique','Practice','Práctica'), tr('Ta voix, ton rythme et ta structure en situation.','Your voice, pace and structure in context.','Tu voz, ritmo y estructura en situación.')],
    ['03', tr('Retour','Feedback','Feedback'), tr('Une force et un geste concret à travailler.','One strength and one concrete action to practise.','Una fortaleza y una acción concreta que practicar.')],
    ['04', tr('Adaptation','Adaptation','Adaptación'), tr('Le prochain exercice évolue avec ton profil.','The next exercise evolves with your profile.','El siguiente ejercicio evoluciona con tu perfil.')],
  ];
  return <section className="ora-v2__engine"><div className="ora-v2__engine-copy"><p className="ora-v2__eyebrow"><span/> {tr('LE MOTEUR ORA','THE ORA ENGINE','EL MOTOR ORA')}</p><h2>{tr('Chaque prise de parole prépare la suivante.','Every speaking session prepares the next.','Cada práctica prepara la siguiente.')}</h2><p>{tr('Le Communication DNA conserve l’évolution des compétences. Le Decision Engine s’en sert pour choisir la mission qui a le plus de valeur maintenant — pas une suite générique d’exercices.','Communication DNA tracks skill development. The Decision Engine uses it to select the most valuable mission now — rather than a generic sequence of exercises.','Communication DNA registra la evolución de las habilidades. Decision Engine lo utiliza para elegir la misión más útil ahora, no una serie genérica de ejercicios.')}</p><div className="ora-v2__dna"><div><small>COMMUNICATION DNA</small><b>{tr('Clarté','Clarity','Claridad')}</b><i><span style={{width:'84%'}}/></i><b>{tr('Structure','Structure','Estructura')}</b><i><span style={{width:'68%'}}/></i><b>{tr('Impact','Impact','Impacto')}</b><i><span style={{width:'57%'}}/></i></div><div className="ora-v2__decision"><small>DECISION ENGINE</small><span>{tr('OBJECTIF','GOAL','OBJETIVO')}</span><span>{tr('HISTORIQUE','HISTORY','HISTORIAL')}</span><span>{tr('PROGRÈS','PROGRESS','PROGRESO')}</span><b>{tr('Mission suivante','Next mission','Siguiente misión')} ↗</b></div></div></div><div className="ora-v2__engine-loop">{steps.map(([n,title,copy], index)=><article key={title}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div>{index < steps.length - 1 && <i>↓</i>}</article>)}</div></section>;
}

export default function OraProject() {
  const { translate: tr } = useLanguage();
  return <main className="ora-v2 page-enter">
    <Seo title={tr('ORA — Application mobile de prise de parole — KODELUME','ORA — Mobile speaking practice app — KODELUME','ORA — Aplicación móvil de expresión oral — KODELUME')} description={tr('ORA aide à prendre confiance à l’oral grâce à des défis courts, un coach bienveillant et une progression visible.','ORA builds speaking confidence through short challenges, thoughtful coaching and visible progress.','ORA ayuda a ganar confianza al hablar mediante retos breves y progreso visible.')} path="/projects/ora" />
    <section className="ora-v2__hero"><div className="ora-v2__hero-copy"><p className="ora-v2__eyebrow"><span/> ORA · AI COMMUNICATION COACH</p><h1>{tr('Ta voix.','Your voice.','Tu voz.')}<br/><em>{tr('Ton aura.','Your aura.','Tu aura.')}</em><br/>{tr('Ton impact.','Your impact.','Tu impacto.')}</h1><p>{tr('Un parcours de coaching qui transforme quelques minutes de pratique vocale en progression durable et personnalisée.','A coaching journey that turns a few minutes of speaking practice into lasting, personalised progress.','Un recorrido de coaching que convierte unos minutos de práctica oral en un progreso duradero y personalizado.')}</p><div><span>PRODUCT DESIGN</span><span>REACT NATIVE</span><span>DECISION ENGINE</span></div></div><div className="ora-v2__hero-visual"><i className="ora-v2__halo"/><Phone screen={<PracticeScreen tr={tr}/>}/><div className="ora-v2__float ora-v2__float--xp"><small>{tr('SESSION','SESSION','SESIÓN')}</small><b>+50 XP</b></div><div className="ora-v2__float ora-v2__float--calm"><small>COMMUNICATION DNA</small><b>{tr('Profil enrichi','Profile updated','Perfil actualizado')}</b></div></div></section>
    <section className="ora-v2__problem"><p className="ora-v2__eyebrow"><span/> {tr('LE POINT DE DÉPART','THE STARTING POINT','EL PUNTO DE PARTIDA')}</p><h2>{tr('La confiance ne se lit pas. Elle se pratique.','You cannot read your way into confidence. You practise it.','La confianza no se lee. Se practica.')}</h2><p>{tr('Présenter une idée, réussir un entretien ou simplement oser intervenir demande de la répétition. ORA transforme cet effort en un rituel court, concret et encourageant.','Presenting an idea, succeeding in an interview or simply speaking up takes repetition. ORA turns that effort into a short and encouraging ritual.','Presentar una idea, afrontar una entrevista o atreverse a intervenir requiere práctica. ORA lo convierte en un ritual breve y motivador.')}</p></section>
    <section className="ora-v2__journey"><header><p className="ora-v2__eyebrow"><span/> {tr('L’EXPÉRIENCE','THE EXPERIENCE','LA EXPERIENCIA')}</p><h2>{tr('Choisir.','Choose.','Elegir.')}<br/>{tr('Parler.','Speak.','Hablar.')}<br/><em>{tr('Progresser.','Progress.','Progresar.')}</em></h2></header><div className="ora-v2__phones"><article><div><span>01</span><h3>{tr('Une mission pertinente','A relevant mission','Una misión relevante')}</h3><p>{tr('Improvisation, entretien, pitch ou storytelling selon le niveau et l’objectif.','Improvisation, interview, pitch or storytelling based on level and goal.','Improvisación, entrevista, pitch o storytelling según el nivel y el objetivo.')}</p></div><Phone screen={<DiscoverScreen tr={tr}/>}/></article><article><div><span>02</span><h3>{tr('La pratique au centre','Practice at the centre','La práctica en el centro')}</h3><p>{tr('Un environnement calme, sans jugement, conçu pour laisser toute la place à la voix.','A calm, judgement-free space designed to put the voice first.','Un entorno tranquilo y sin juicios diseñado para dar prioridad a la voz.')}</p></div><Phone screen={<PracticeScreen tr={tr}/>}/></article><article><div><span>03</span><h3>{tr('Un coaching qui apprend','Coaching that learns','Un coaching que aprende')}</h3><p>{tr('Le feedback enrichit le profil et rend chaque nouvelle mission plus pertinente.','Feedback enriches the profile and makes every new mission more relevant.','El feedback enriquece el perfil y hace que cada nueva misión sea más relevante.')}</p></div><Phone screen={<ProgressScreen tr={tr}/>}/></article></div></section>
    <CoachingLoop tr={tr} />
    <section className="ora-v2__principles"><p className="ora-v2__eyebrow"><span/> {tr('PRINCIPES PRODUIT','PRODUCT PRINCIPLES','PRINCIPIOS DE PRODUCTO')}</p><div><article><b>01</b><h3>{tr('Bienveillant','Supportive','Amable')}</h3><p>{tr('Le coach accompagne la pratique sans noter la personne.','The coach supports practice without grading the person.','El coach acompaña la práctica sin calificar a la persona.')}</p></article><article><b>02</b><h3>{tr('Actionnable','Actionable','Práctico')}</h3><p>{tr('Chaque session se termine par un conseil précis.','Every session ends with one precise recommendation.','Cada sesión termina con un consejo concreto.')}</p></article><article><b>03</b><h3>{tr('Progressif','Progressive','Progresivo')}</h3><p>{tr('L’Aura récompense la régularité, jamais la perfection.','Aura rewards consistency, never perfection.','Aura premia la constancia, nunca la perfección.')}</p></article></div></section>
    <section className="ora-v2__footer"><div><p className="ora-v2__eyebrow"><span/> {tr('EN DÉVELOPPEMENT','IN DEVELOPMENT','EN DESARROLLO')}</p><h2>{tr('Une vision claire. Un produit qui prend forme.','A clear vision. A product taking shape.','Una visión clara. Un producto que toma forma.')}</h2></div><Link to="/references">{tr('Retour aux références','Back to work','Volver a proyectos')} <span>↗</span></Link></section>
  </main>;
}
