import React from 'react';
import { Link } from 'react-router-dom';
import Seo from './Seo';
import { useLanguage } from './language-state';

function SolWindow({ tr }) {
  return (
    <div className="sol-window" aria-label={tr('Interface de l’extension de recherche Sol','Sol research browser extension interface','Interfaz de la extensión de investigación Sol')}>
      <div className="sol-window__bar"><span /><span /><span /><b>SOL / INTELLIGENCE</b><i>⌘ K</i></div>
      <div className="sol-window__body">
        <aside><strong>SOL</strong><small>{tr('Assistant de recherche','Research companion','Asistente de investigación')}</small><div className="sol-window__side-active">{tr('Nouvelle recherche','New investigation','Nueva investigación')} <b>+</b></div><p>{tr('Récentes','Recent','Recientes')}</p><div>WIF / token brief</div><div>JUP / wallet flow</div></aside>
        <main><div className="sol-window__query"><span>⌕</span><strong>{tr('Collez une adresse ou posez une question','Paste an address or ask a question','Pega una dirección o haz una pregunta')}</strong><b>↵</b></div><div className="sol-window__answer"><div className="sol-window__answer-meta"><span className="sol-dot" /> {tr('RÉPONSE VÉRIFIÉE','VERIFIED ANSWER','RESPUESTA VERIFICADA')} <time>{tr('mise à jour il y a 2 min','updated 2m ago','actualizada hace 2 min')}</time></div><h3>{tr('Qu’est-ce qui a changé autour de ce token ?','What changed around this token?','¿Qué cambió alrededor de este token?')}</h3><p>{tr('L’activité a augmenté sur trois wallets indépendants. Le signal est récent, mais leur relation reste à confirmer.','Trading activity increased across three independent wallets. The signal is fresh, but their relationship remains unconfirmed.','La actividad aumentó en tres wallets independientes. La señal es reciente, pero su relación aún no está confirmada.')}</p><div className="sol-window__sources"><span>DEXSCREENER</span><span>HELIUS</span><span>{tr('SOURCES PUBLIQUES','PUBLIC SOURCES','FUENTES PÚBLICAS')}</span></div><div className="sol-window__evidence"><span>01</span><b>{tr('Chronologie des preuves','Evidence timeline','Cronología de pruebas')}</b><small>{tr('12 sources · 4 événements','12 sources · 4 events','12 fuentes · 4 eventos')}</small><em>↗</em></div><div className="sol-window__evidence"><span>02</span><b>{tr('Contexte du wallet','Wallet context','Contexto del wallet')}</b><small>{tr('Première observation · 08 sept. 2026','First observed · 08 Sep 2026','Primera observación · 08 sep. 2026')}</small><em>↗</em></div><div className="sol-window__confidence"><span>{tr('CONFIANCE','CONFIDENCE','CONFIANZA')}</span><strong>{tr('Modérée','Moderate','Moderada')}</strong><i /></div></div></main>
      </div>
    </div>
  );
}

function SolSignalGraph({ tr }) {
  return <div className="sol-signal" role="img" aria-label={tr('Pipeline de recherche Solana, des sources à une réponse vérifiée','Solana research pipeline, from sources to a verified answer','Pipeline de investigación Solana, de las fuentes a una respuesta verificada')}><div className="sol-signal__top"><span>SOL / RETRIEVAL MAP</span><b>{tr('CONTEXTE ACTIF','LIVE CONTEXT','CONTEXTO ACTIVO')}</b></div><div className="sol-signal__canvas"><svg viewBox="0 0 900 430" aria-hidden="true"><path d="M105 90C230 90 205 215 330 215M105 215H330M105 340C230 340 205 215 330 215M405 215H555M630 215h165"/><path className="sol-signal__pulse" d="M105 90C230 90 205 215 330 215H555C650 215 675 215 795 215"/></svg><div className="sol-signal__node source one"><small>01 / MARKET</small><b>DexScreener</b><span>{tr('prix · liquidité','price · liquidity','precio · liquidez')}</span></div><div className="sol-signal__node source two"><small>02 / CHAIN</small><b>Helius</b><span>wallets · transfers</span></div><div className="sol-signal__node source three"><small>03 / CULTURE</small><b>{tr('Sources publiques','Public sources','Fuentes públicas')}</b><span>{tr('récits · contexte','narratives · context','narrativas · contexto')}</span></div><div className="sol-signal__node retrieval"><small>RETRIEVAL</small><b>{tr('Ensemble de preuves','Evidence set','Conjunto de pruebas')}</b><span>12 sources</span></div><div className="sol-signal__node reasoning"><small>REASONING</small><b>{tr('Observé / inféré','Observed / inferred','Observado / inferido')}</b><span>{tr('inconnues préservées','unknowns preserved','incógnitas preservadas')}</span></div><div className="sol-signal__node answer"><i/><small>{tr('RÉPONSE','ANSWER','RESPUESTA')}</small><b>{tr('Confiance modérée','Moderate confidence','Confianza moderada')}</b><span>{tr('4 affirmations · 4 citations','4 claims · 4 citations','4 afirmaciones · 4 citas')}</span></div></div><footer><span>{tr('Sources toujours visibles','Sources remain visible','Fuentes siempre visibles')}</span><span>{tr('Confiance explicite','Confidence is explicit','Confianza explícita')}</span><span>{tr('Aucune lacune inventée','No invented gaps','Ningún vacío inventado')}</span></footer></div>;
}

function ProcessIllustration({ type, tr }) {
  const labels = {
    resolve: [tr('ADRESSE','ADDRESS','DIRECCIÓN'), tr('MINT RÉSOLU','MINT RESOLVED','MINT RESUELTO')],
    collect: ['3 SOURCES', tr('ENSEMBLE DE PREUVES','EVIDENCE SET','CONJUNTO DE PRUEBAS')],
    explain: [tr('FAIT / INFÉRENCE','FACT / INFERENCE','HECHO / INFERENCIA'), tr('CONTEXTE COMPOSÉ','CONTEXT COMPOSED','CONTEXTO COMPUESTO')],
    verify: [tr('AFFIRMATION → SOURCE','CLAIM → SOURCE','AFIRMACIÓN → FUENTE'), tr('CONFIANCE EXPLICITE','CONFIDENCE EXPLICIT','CONFIANZA EXPLÍCITA')],
  };
  const [from, to] = labels[type];
  return <div className={`sol-process-art sol-process-art--${type}`} aria-hidden="true"><img src={`/sol/process/${type}.png`} alt="" loading="lazy"/><span>{from}</span><b>{to}</b></div>;
}

export default function SolProject() {
  const { translate: tr } = useLanguage();
  return <div className="project-detail sol-project page-enter min-h-screen bg-[#11110f] text-[#f8f5ed]"><Seo title={tr('Sol — Intelligence Solana et assistant navigateur — KODELUME', 'Sol — Solana intelligence browser companion — KODELUME', 'Sol — Inteligencia de Solana y asistente de navegador — KODELUME')} description={tr('Un assistant conversationnel pour comprendre les tokens, les wallets et les signaux Solana à partir de sources vérifiables.', 'A conversational browser companion for understanding Solana tokens, wallets and signals through verifiable sources.', 'Un asistente conversacional para entender tokens, wallets y señales de Solana a partir de fuentes verificables.')} path="/projects/sol" />
    <section className="project-detail__hero"><div><p className="project-kicker"><span /> {tr('SOL / RECHERCHE PRODUIT','SOL / PRODUCT RESEARCH','SOL / INVESTIGACIÓN DE PRODUCTO')}</p><h1>{tr('Comprendre','Understand','Entender')}<br /><em>{tr('le signal.','the signal.','la señal.')}</em></h1><p className="project-detail__intro">{tr('Un copilote de recherche pour les traders et développeurs Solana : une réponse claire, reliée à ses preuves, directement dans le navigateur.', 'A research companion for Solana traders and developers: clear answers connected to their evidence, directly in the browser.', 'Un compañero de investigación para traders y desarrolladores de Solana: respuestas claras conectadas a sus pruebas, directamente en el navegador.')}</p><div className="project-tags"><span>RAG</span><span>CHROME EXTENSION</span><span>SOLANA DATA</span></div></div><SolWindow tr={tr} /></section>
    <section className="project-detail__content"><div><p className="project-kicker"><span /> {tr('LE PRODUIT','THE PRODUCT','EL PRODUCTO')}</p><h2>{tr('La recherche, sans les onglets.', 'Research without the tab overload.', 'Investigación sin exceso de pestañas.')}</h2></div><div className="project-detail__copy"><p>{tr('Sol rassemble signaux culturels, données blockchain et sources publiques dans un même fil de conversation. Chaque réponse distingue les faits observés, les hypothèses et ce qui reste inconnu.', 'Sol brings cultural signals, blockchain data and public sources into one conversational thread. Every answer separates observed facts, hypotheses and what remains unknown.', 'Sol reúne señales culturales, datos de blockchain y fuentes públicas en un mismo hilo conversacional. Cada respuesta separa hechos observados, hipótesis y lo que sigue sin confirmar.')}</p><div className="project-detail__metrics"><div><strong>01</strong><span>{tr('Adresse → contexte', 'Address → context', 'Dirección → contexto')}</span></div><div><strong>02</strong><span>{tr('Réponse → preuves', 'Answer → evidence', 'Respuesta → pruebas')}</span></div><div><strong>03</strong><span>{tr('Question → suite', 'Question → follow-up', 'Pregunta → seguimiento')}</span></div></div></div></section>
    <section className="sol-signal-section"><div><p className="project-kicker"><span /> {tr('SOUS LA RÉPONSE','UNDER THE ANSWER','BAJO LA RESPUESTA')}</p><h2>{tr('Une réponse que l’on peut inspecter.', 'An answer you can inspect.', 'Una respuesta que se puede inspeccionar.')}</h2></div><SolSignalGraph tr={tr} /></section>
    <section className="sol-process"><div className="sol-process__intro"><p className="project-kicker"><span /> {tr('LE PROCESSUS','THE PROCESS','EL PROCESO')}</p><h2>{tr('Une réponse fiable se construit par étapes.', 'A reliable answer is built in stages.', 'Una respuesta fiable se construye por etapas.')}</h2><p>{tr('L’IA explique les données récupérées. Elle ne remplit pas les blancs et ne transforme pas un signal en certitude.', 'The AI explains retrieved data. It does not fill gaps or turn a signal into certainty.', 'La IA explica los datos recuperados. No rellena vacíos ni convierte una señal en certeza.')}</p></div><div className="sol-process__steps"><article><span>01</span><ProcessIllustration type="resolve" tr={tr}/><h3>{tr('Résoudre','Resolve','Resolver')}</h3><p>{tr('Identifier l’adresse, le mint et les entités associées.','Identify the address, mint and related entities.','Identificar la dirección, el mint y las entidades asociadas.')}</p></article><article><span>02</span><ProcessIllustration type="collect" tr={tr}/><h3>{tr('Collecter','Collect','Recopilar')}</h3><p>{tr('Rassembler transactions, wallets, liquidité et sources publiques.','Gather transactions, wallets, liquidity and public sources.','Reunir transacciones, wallets, liquidez y fuentes públicas.')}</p></article><article><span>03</span><ProcessIllustration type="explain" tr={tr}/><h3>{tr('Expliquer','Explain','Explicar')}</h3><p>{tr('Composer une synthèse courte avec le contexte qui compte.','Compose a concise synthesis with the context that matters.','Componer una síntesis breve con el contexto relevante.')}</p></article><article><span>04</span><ProcessIllustration type="verify" tr={tr}/><h3>{tr('Vérifier','Verify','Verificar')}</h3><p>{tr('Relier chaque affirmation à une preuve et afficher les inconnues.','Connect every claim to evidence and expose unknowns.','Vincular cada afirmación a una prueba y mostrar las incógnitas.')}</p></article></div></section>
    <section className="project-detail__cta"><p className="project-kicker"><span /> {tr('STATUT / PROTOTYPE PRIVÉ','STATUS / PRIVATE PROTOTYPE','ESTADO / PROTOTIPO PRIVADO')}</p><h2>{tr('Une interface pour penser avant d’agir.', 'An interface for thinking before acting.', 'Una interfaz para pensar antes de actuar.')}</h2><Link to="/references">{tr('Retour aux références', 'Back to work', 'Volver a proyectos')} <span>↗</span></Link></section>
  </div>;
}
